/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.qoopo.engine3d.editor.entity.componentes.fisica.vehiculo;

import java.util.HashMap;
import java.util.Map;

import javax.swing.DefaultComboBoxModel;

import net.qoopo.engine.core.entity.Entity;
import net.qoopo.engine.core.entity.component.EntityComponent;
import net.qoopo.engine.core.entity.component.mesh.Mesh;
import net.qoopo.engine.core.entity.component.mesh.primitive.Vertex;
import net.qoopo.engine.core.entity.component.physics.collision.detector.shape.primitivas.AABB;
import net.qoopo.engine.core.entity.component.physics.vehiculo.QVehiculoControl;
import net.qoopo.engine.core.util.ComponentUtil;
import net.qoopo.engine3d.editor.Principal;

/**
 *
 * @author alberto
 */
public class PnlControlVehiculo extends javax.swing.JPanel {

    private QVehiculoControl componente;
    private Map<String, Entity> mapa = new HashMap<>();

    /**
     * Creates new form PnlCubo
     */
    public PnlControlVehiculo(QVehiculoControl componente) {
        initComponents();
        this.componente = componente;

        DefaultComboBoxModel modelo = new DefaultComboBoxModel<>();
        for (Entity entidad : Principal.instancia.getEscena().getEntities()) {
            for (EntityComponent comp : entidad.getComponents()) {
                if (comp instanceof Mesh) { // que tenga una geometria
                    modelo.addElement(entidad.getName());
                    mapa.put(entidad.getName(), entidad);
                }
            }
        }
        cboRueda.setModel(modelo);
        // if (componente.getB() != null) {
        // cboFisico.setSelectedItem(componente.getB().entity.nombre);
        // }
        aplicarCambios();
        actualizarListaRuedas();
    }

    private void aplicarCambios() {
        // componente.setB(mapa.get(cboFisico.getSelectedItem().toString()));
        // componente.setRadio(Float.parseFloat(txtRadio.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboRueda = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblChasis = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Control Vehículo"));

        jLabel1.setText("Agregar rueda:");

        cboRueda.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboRueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRuedaActionPerformed(evt);
            }
        });

        jLabel2.setText("Chasis:");

        lblChasis.setText("N/A");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RUEDAS");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cboRueda, 0, 249, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChasis, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jSeparator2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(lblChasis))
                                .addGap(9, 9, 9)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboRueda, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));
    }// </editor-fold>//GEN-END:initComponents

    private void cboRuedaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cboRuedaActionPerformed
        // intenta calcular el ancho y el radi ode la rueda

        Entity entidadRueda = mapa.get(cboRueda.getSelectedItem().toString());
        if (entidadRueda != null) {
            Mesh geometria = ComponentUtil.getMesh(entidadRueda);
            AABB tmp = new AABB(geometria.vertexList[0].clone(), geometria.vertexList[0].clone());

            for (Vertex vertice : geometria.vertexList) {
                if (vertice.location.x < tmp.aabMinimo.location.x) {
                    tmp.aabMinimo.location.x = vertice.location.x;
                }
                if (vertice.location.y < tmp.aabMinimo.location.y) {
                    tmp.aabMinimo.location.y = vertice.location.y;
                }
                if (vertice.location.z < tmp.aabMinimo.location.z) {
                    tmp.aabMinimo.location.z = vertice.location.z;
                }
                if (vertice.location.x > tmp.aabMaximo.location.x) {
                    tmp.aabMaximo.location.x = vertice.location.x;
                }
                if (vertice.location.y > tmp.aabMaximo.location.y) {
                    tmp.aabMaximo.location.y = vertice.location.y;
                }
                if (vertice.location.z > tmp.aabMaximo.location.z) {
                    tmp.aabMaximo.location.z = vertice.location.z;
                }
            }
        }
    }// GEN-LAST:event_cboRuedaActionPerformed

    private void actualizarListaRuedas() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboRueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblChasis;
    // End of variables declaration//GEN-END:variables
}
